(define (problem gsoko1a)
(:domain istambul)
(:objects cr sp t f ps st so p1 p2 v0 v1 v2 v3 owoce tkanina przyprawy kawa rubin)
(:init
	    (pole cr)
	    (pole sp)
	    (pole t)
	    (pole f)
	    (pole ps)
	    (pole st)
	    (pole so)
	    (sasiaduje cr sp)
	    (sasiaduje sp cr)
	    (sasiaduje sp f)
	    (sasiaduje sp t)
	    (sasiaduje t sp)
	    (sasiaduje f sp)
	    (sasiaduje f st)
	    (sasiaduje ps st)
	    (sasiaduje st ps)
	    (sasiaduje st so)
	    (sasiaduje so st)
        (linia cr t)
        (linia t cr)
        (linia sp st)
        (linia st sp)
        (linia ps so)
        (linia so ps)
        (pom p1)
        (pom p2)
	    (kupiec f)
        (pomocnik-z-nami p1)
	    (pomocnik-z-nami p2)
	    (przyprawy sp)
	    (owoce so)
	    (tkanina st)
	    (czarny-rynek cr)
	    (targowisko t)
	    (fontanna f)
	    (palac ps)
	    (wozek owoce v1)
	    (wozek owoce v2)
	    (ilosc-owoce v2)
	    (ilosc-tkanin v0)
	    (ilosc-przypraw v0)
	    (succ v0 v1)
	    (succ v0 v2)
	    (succ v0 v3)
	    (succ v1 v2)
	    (succ v1 v3)
	    (succ v2 v3)
	    (ilosc-kawy v0)
)
(:goal (and
        (kupiec ps)
       (wozek rubin v1)
))
)