(define (problem gsoko1a)
(:domain hanoi)
(:objects x y z k1 k2 k3 k4 k5)
(:init
        (palik x)
        (palik y)
        (palik z)
        (krazek k1)
        (krazek k2)
        (krazek k3)
        (krazek k4)
        (krazek k5)
		(na-paliku k1 x)
		(na-paliku k2 x)
		(na-paliku k3 x)
		(na-paliku k4 x)
		(na-paliku k5 x)
		(na-ziemi k5)
		(na-krazku k4 k5)
		(na-krazku k3 k4)
		(na-krazku k2 k3)
		(na-krazku k1 k2)
		(mniejszy k1 k2)
		(mniejszy k1 k3)
		(mniejszy k1 k4)
		(mniejszy k1 k5)
		(mniejszy k2 k3)
		(mniejszy k2 k4)
		(mniejszy k2 k5)
		(mniejszy k3 k4)
		(mniejszy k3 k5)
		(mniejszy k4 k5)
)
(:goal (and
        (palik x)
        (palik y)
        (palik z)
        (krazek k1)
        (krazek k2)
        (krazek k3)
        (krazek k4)
        (krazek k5)
        (na-paliku k1 z)
		(na-paliku k2 z)
		(na-paliku k3 z)
		(na-paliku k4 z)
		(na-paliku k5 z)
		(na-ziemi k5)
		(na-krazku k4 k5)
		(na-krazku k3 k4)
		(na-krazku k2 k3)
		(na-krazku k1 k2)
		(mniejszy k1 k2)
		(mniejszy k1 k3)
		(mniejszy k1 k4)
		(mniejszy k1 k5)
		(mniejszy k2 k3)
		(mniejszy k2 k4)
		(mniejszy k2 k5)
		(mniejszy k3 k4)
		(mniejszy k3 k5)
		(mniejszy k4 k5)
))
)